<?php
    if (!$this->isEnabled()) {
        return false;
    }

    if ($this->isCustomerTag()) {
        $customerIdentifier = $this->getKondutoIdentifier();
    }
?>
<script type="text/javascript">
    var __kdt = __kdt || [];
    __kdt.push({"public_key":"<?php echo $this->getPublicKey(); ?>"});
    
    <?php if (isset($customerIdentifier)): ?>
    __kdt.push({"customer_id":"<?php echo $customerIdentifier ?>"});
    <?php endif; ?>
    
    (function() {
        var kdt = document.createElement("script");
        kdt.id = "kdtjs"; kdt.type = "text/javascript"; kdt.async = true;
        kdt.src = "https://i.k-analytix.com/k.js";
        var s = document.getElementsByTagName("body")[0];
        s.parentNode.insertBefore(kdt, s);
    })();
</script>