<?php
    if (!$this->isEnabled()) {
        return false;
    }
    $customerId = $this->getCustomerId();
?>
<script type="text/javascript">
    var __kdt = __kdt || [];
    __kdt.push({"public_key":"<?php echo $this->getPublicKey(); ?>"}); // A chave pública identifica a sua loja
    
    <?php if (isset($customerId)): ?>
    __kdt.push({"customer_id":"<?php echo $customerId ?>"});
    <?php endif; ?>
    
    (function() {
        var kdt = document.createElement("script");
        kdt.id = "kdtjs"; kdt.type = "text/javascript"; kdt.async = true;
        kdt.src = "https://i.k-analytix.com/k.js";
        var s = document.getElementsByTagName("body")[0];
        s.parentNode.insertBefore(kdt, s);
    })();
</script>